server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driver-class-name: ${db.driver}
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}

  jpa:
    open-in-view: true  #lazy 로딩이 가능하게 함. https://www.youtube.com/watch?v=fSXh4hWJtKo&list=PL93mKxaRDidECgjOBjPgI3Dyo8ka6Ilqm&index=45 참고
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false  #jpa의 기본 넘버링 전략을 사용하지 않음(DB 테이블의 넘버링 방식을 따라감)
    show-sql: true
    properties:
      hibernate.format_sql: true


  jackson:
    serialization:
      fail-on-empty-beans: false
